version: "2"
run:
  build-tags:
    - e2e
  modules-download-mode: vendor
  issues-exit-code: 1
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gomodguard
    - gosec
    - govet
    - ireturn
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
  uniq-by-line: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
