linters-settings:
  linters:
    disable-all: true
    enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gocritic
    - golint
  output:
    uniq-by-line: false
  issues:
    exclude-rules:
    - path: _test\.go
      linters:
      - errcheck
      - gosec
    max-issues-per-linter: 0
    max-same-issues: 0
  run:
    issues-exit-code: 1
    build-tags:
    - e2e
    skip-dirs:
    - vendor
    timeout: 10m
    modules-download-mode: vendor
