# Documentation: https://golangci-lint.run/usage/configuration/
linters-settings:
linters:
  enable:
  - bodyclose
  - containedctx
  - decorder
  - depguard
  - dogsled
  - dupl
  - dupword
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - goconst
  - gocritic
  - gofmt
  - goimports
  - gomodguard
  - gosec
  - gosimple
  - govet
  - ireturn
  - misspell
  - revive
  - staticheck
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - whitespace
  - wrapcheck
  # Enabling presets means that new linters that we automatically adopt new
  # linters that augment a preset. This also opts us in for replacement linters
  # when a linter is deprecated.
  presets:
  - bugs
  - comment
  - complexity
  - error
  - format
  - import
  - metalinter
  - module
  - performance
  - sql
  - style
  - test
  - unused
output:
  uniq-by-line: false
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
  include:
  # Enable off-by-default rules for revive requiring that all exported elements have a properly formatted comment.
  - EXC0012 # https://golangci-lint.run/usage/false-positives/#exc0012
  - EXC0014 # https://golangci-lint.run/usage/false-positives/#exc0014
run:
  issues-exit-code: 1
  build-tags:
  - e2e
  skip-dirs:
  - vendor
  timeout: 10m
  modules-download-mode: vendor
