# Documentation: https://golangci-lint.run/usage/configuration/
linters-settings:
linters:
  disable-all: true
  enable:
  - bodyclose
  - decorder
  - depguard
  - dupword
  - errcheck
  - gocritic
  - gofmt
  - goimports
  - gomodguard
  - gosec
  - gosimple
  - govet
  - misspell
  - revive
  - thelper
  - typecheck
  - unconvert
  - unused
  - usestdlibvars
  - whitespace
output:
  uniq-by-line: false
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  issues-exit-code: 1
  build-tags:
  - e2e
  skip-dirs:
  - vendor
  timeout: 10m
  modules-download-mode: vendor
