// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v2/chains.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry struct {
	Svid                 string            `protobuf:"bytes,1,opt,name=svid,proto3" json:"svid,omitempty"`
	Signatures           map[string]string `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Uid                  string            `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d9f909ba79f0cc, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetSvid() string {
	if m != nil {
		return m.Svid
	}
	return ""
}

func (m *Entry) GetSignatures() map[string]string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Entry) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d9f909ba79f0cc, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type EntryRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryRequest) Reset()         { *m = EntryRequest{} }
func (m *EntryRequest) String() string { return proto.CompactTextString(m) }
func (*EntryRequest) ProtoMessage()    {}
func (*EntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d9f909ba79f0cc, []int{2}
}

func (m *EntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryRequest.Unmarshal(m, b)
}
func (m *EntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryRequest.Marshal(b, m, deterministic)
}
func (m *EntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryRequest.Merge(m, src)
}
func (m *EntryRequest) XXX_Size() int {
	return xxx_messageInfo_EntryRequest.Size(m)
}
func (m *EntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryRequest proto.InternalMessageInfo

func (m *EntryRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterType((*Entry)(nil), "proto.v2.Entry")
	proto.RegisterMapType((map[string]string)(nil), "proto.v2.Entry.SignaturesEntry")
	proto.RegisterType((*Empty)(nil), "proto.v2.Empty")
	proto.RegisterType((*EntryRequest)(nil), "proto.v2.EntryRequest")
}

func init() { proto.RegisterFile("v2/chains.proto", fileDescriptor_b3d9f909ba79f0cc) }

var fileDescriptor_b3d9f909ba79f0cc = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x4a, 0xc3, 0x40,
	0x14, 0xc6, 0x99, 0xd4, 0x6a, 0x7d, 0x2a, 0x29, 0x83, 0x4a, 0x08, 0x82, 0x21, 0xab, 0xe2, 0x22,
	0x81, 0xb8, 0x91, 0x82, 0x88, 0x96, 0xe2, 0xbe, 0x75, 0xe5, 0x6e, 0x9a, 0x19, 0xd2, 0xa1, 0xed,
	0x4c, 0x4d, 0x66, 0x02, 0x45, 0xdc, 0x78, 0x05, 0x6f, 0x21, 0x78, 0x1a, 0xaf, 0xe0, 0x41, 0x24,
	0xaf, 0x4d, 0xad, 0x59, 0xbd, 0x3f, 0x7c, 0xdf, 0xf7, 0x63, 0xde, 0x80, 0x5b, 0x26, 0x71, 0x3a,
	0x65, 0x52, 0x15, 0xd1, 0x32, 0xd7, 0x46, 0xd3, 0x0e, 0x96, 0xa8, 0x4c, 0xfc, 0x8b, 0x4c, 0xeb,
	0x6c, 0x2e, 0x62, 0xb6, 0x94, 0x31, 0x53, 0x4a, 0x1b, 0x66, 0xa4, 0xae, 0x75, 0xe1, 0x17, 0x81,
	0xf6, 0x50, 0x99, 0x7c, 0x45, 0x29, 0xec, 0x15, 0xa5, 0xe4, 0x1e, 0x09, 0x48, 0xef, 0x70, 0x84,
	0x3d, 0xbd, 0x03, 0x28, 0x64, 0xa6, 0x98, 0xb1, 0xb9, 0x28, 0x3c, 0x27, 0x68, 0xf5, 0x8e, 0x92,
	0xcb, 0xa8, 0x8e, 0x8e, 0xd0, 0x18, 0x8d, 0xb7, 0x0a, 0x9c, 0x47, 0x3b, 0x16, 0xda, 0x85, 0x96,
	0x95, 0xdc, 0x6b, 0x61, 0x66, 0xd5, 0xfa, 0xb7, 0xe0, 0x36, 0x0c, 0x95, 0x68, 0x26, 0x56, 0x1b,
	0x70, 0xd5, 0xd2, 0x53, 0x68, 0x97, 0x6c, 0x6e, 0x85, 0xe7, 0xe0, 0x6e, 0x3d, 0xf4, 0x9d, 0x1b,
	0x12, 0x1e, 0x40, 0x7b, 0xb8, 0x58, 0x9a, 0x55, 0x18, 0xc0, 0xf1, 0x1a, 0x27, 0x5e, 0xac, 0x28,
	0x4c, 0x4d, 0x22, 0x5b, 0x52, 0xf2, 0x49, 0xe0, 0x64, 0x80, 0x37, 0x19, 0x8b, 0xbc, 0x94, 0xa9,
	0xa0, 0x03, 0xe8, 0xdc, 0x73, 0xbe, 0x86, 0xba, 0x8d, 0x67, 0xf8, 0xbb, 0x0b, 0x24, 0x9c, 0xbd,
	0x7f, 0xff, 0x7c, 0x38, 0x6e, 0x08, 0x78, 0x3a, 0x51, 0x89, 0xfa, 0xe4, 0x8a, 0x3e, 0x81, 0xfb,
	0x28, 0xcc, 0x3f, 0xf6, 0x79, 0x23, 0x6b, 0xb3, 0xf7, 0x9b, 0x8c, 0xd0, 0xc3, 0x48, 0x4a, 0xbb,
	0x7f, 0x91, 0xf1, 0xab, 0x95, 0xfc, 0xed, 0x21, 0x7c, 0x0e, 0x32, 0x69, 0xa6, 0x76, 0x12, 0xa5,
	0x7a, 0x11, 0x1b, 0x31, 0x33, 0x5a, 0xa5, 0x7c, 0xf3, 0xa7, 0x31, 0xc6, 0x4c, 0xf6, 0xb1, 0x5c,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xa5, 0x2f, 0x98, 0xed, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChainsServiceClient is the client API for ChainsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainsServiceClient interface {
	AddEntry(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Empty, error)
	GetEntryRequest(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*Entry, error)
}

type chainsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChainsServiceClient(cc grpc.ClientConnInterface) ChainsServiceClient {
	return &chainsServiceClient{cc}
}

func (c *chainsServiceClient) AddEntry(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.v2.ChainsService/AddEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsServiceClient) GetEntryRequest(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*Entry, error) {
	out := new(Entry)
	err := c.cc.Invoke(ctx, "/proto.v2.ChainsService/GetEntryRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainsServiceServer is the server API for ChainsService service.
type ChainsServiceServer interface {
	AddEntry(context.Context, *Entry) (*Empty, error)
	GetEntryRequest(context.Context, *EntryRequest) (*Entry, error)
}

// UnimplementedChainsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChainsServiceServer struct {
}

func (*UnimplementedChainsServiceServer) AddEntry(ctx context.Context, req *Entry) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEntry not implemented")
}
func (*UnimplementedChainsServiceServer) GetEntryRequest(ctx context.Context, req *EntryRequest) (*Entry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntryRequest not implemented")
}

func RegisterChainsServiceServer(s *grpc.Server, srv ChainsServiceServer) {
	s.RegisterService(&_ChainsService_serviceDesc, srv)
}

func _ChainsService_AddEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsServiceServer).AddEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v2.ChainsService/AddEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsServiceServer).AddEntry(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsService_GetEntryRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsServiceServer).GetEntryRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v2.ChainsService/GetEntryRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsServiceServer).GetEntryRequest(ctx, req.(*EntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v2.ChainsService",
	HandlerType: (*ChainsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEntry",
			Handler:    _ChainsService_AddEntry_Handler,
		},
		{
			MethodName: "GetEntryRequest",
			Handler:    _ChainsService_GetEntryRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/chains.proto",
}
