name: Chains kind E2E Tests


'on':
  workflow_call: {}
# on:
#   pull_request:
#     branches:
#       - main
#       - release-*

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  k8s:
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.k8s-version }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false  # Keep running if one leg fails.
      matrix:
        # Keep in sync with the list of supported releases: https://kubernetes.io/releases/
        # Add latest k8s-version once it is added in https://github.com/sigstore/scaffolding/releases
        k8s-version:
          - v1.32.x
          - v1.33.x
          - v1.34.x
    uses: ./.github/workflows/reusable-e2e.yaml
    with:
      k8s-version: ${{ matrix.k8s-version }}
      pipelines-release: latest
  load-lts-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      versions: ${{ steps.read.outputs.versions }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: read
        run: echo "versions=$(cat .github/pipeline-lts.json | jq -c .)" >> $GITHUB_OUTPUT
  pipelines-lts:
    needs: load-lts-versions
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.pipelines-release }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false  # Keep running if one leg fails.
      matrix:
        pipelines-release: ${{ fromJSON(needs.load-lts-versions.outputs.versions) }}
    uses: ./.github/workflows/reusable-e2e.yaml
    with:
      k8s-version: v1.34.x  # intersection of the latest version and scaffolding
      pipelines-release: ${{ matrix.pipelines-release }}
